package com.jimi.ozone_server.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePersonnelTask<M extends BasePersonnelTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPersonnel(java.lang.Integer personnel) {
		set("personnel", personnel);
	}
	
	public java.lang.Integer getPersonnel() {
		return getInt("personnel");
	}

	public void setTask(java.lang.Integer task) {
		set("task", task);
	}
	
	public java.lang.Integer getTask() {
		return getInt("task");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
