package com.jimi.ozone_server.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskRelation<M extends BaseTaskRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPredecessorTask(java.lang.Integer predecessorTask) {
		set("predecessor_task", predecessorTask);
	}
	
	public java.lang.Integer getPredecessorTask() {
		return getInt("predecessor_task");
	}

	public void setCurrentTask(java.lang.Integer currentTask) {
		set("current_task", currentTask);
	}
	
	public java.lang.Integer getCurrentTask() {
		return getInt("current_task");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}

}
