package com.jimi.ozone_server.comm.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MysqlMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MysqlMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("gantt", "id", Gantt.class);
		arp.addMapping("personnel", "id", Personnel.class);
		arp.addMapping("personnel_classify", "id", PersonnelClassify.class);
		arp.addMapping("personnel_task", "id", PersonnelTask.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("task_classify", "id", TaskClassify.class);
		arp.addMapping("task_relation", "id", TaskRelation.class);
	}
}

